# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessCI
      
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/phpunit@v2
      with:
          bootstrap: admin/lib/vendor/autoload.php
          configuration: admin/tests/phpunit.xml
  test-e2e:
    needs: [test-backend, test-frontend ]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 14.x
       uses: actions/setup-node@v1
       with:
          node-version: 14.x
     - name: Cypress run
       uses: cypress-io/github-action@v2
       with:
          build: npm run build
          start: npm start
     - name: SonarTest
       uses: sonarsource/sonarcloud-github-action@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
    
  deploy:
    needs: test-e2e
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/cache@v1 
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod
    - name: copy front-end via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: vj654.ftp.infomaniak.com
        USERNAME: vj654_test
        PORT: 22
        PASSWORD: ${{ secrets.FORSSH }}
      with:
        source: "./dist/realationnel/"
        target: "/home/clients/3c6135cda21de04b0eadc9b1a9851f53/cube/realationnel"
        strip_components: 3
      
